// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	middleware "loanManagement/middleware"

	mock "github.com/stretchr/testify/mock"
)

// Middleware is an autogenerated mock type for the Middleware type
type Middleware struct {
	mock.Mock
}

type Middleware_Expecter struct {
	mock *mock.Mock
}

func (_m *Middleware) EXPECT() *Middleware_Expecter {
	return &Middleware_Expecter{mock: &_m.Mock}
}

// Auth provides a mock function with given fields:
func (_m *Middleware) Auth() middleware.Auth {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 middleware.Auth
	if rf, ok := ret.Get(0).(func() middleware.Auth); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Auth)
		}
	}

	return r0
}

// Middleware_Auth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Auth'
type Middleware_Auth_Call struct {
	*mock.Call
}

// Auth is a helper method to define mock.On call
func (_e *Middleware_Expecter) Auth() *Middleware_Auth_Call {
	return &Middleware_Auth_Call{Call: _e.mock.On("Auth")}
}

func (_c *Middleware_Auth_Call) Run(run func()) *Middleware_Auth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Middleware_Auth_Call) Return(_a0 middleware.Auth) *Middleware_Auth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Middleware_Auth_Call) RunAndReturn(run func() middleware.Auth) *Middleware_Auth_Call {
	_c.Call.Return(run)
	return _c
}

// Server provides a mock function with given fields:
func (_m *Middleware) Server() middleware.Server {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Server")
	}

	var r0 middleware.Server
	if rf, ok := ret.Get(0).(func() middleware.Server); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Server)
		}
	}

	return r0
}

// Middleware_Server_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Server'
type Middleware_Server_Call struct {
	*mock.Call
}

// Server is a helper method to define mock.On call
func (_e *Middleware_Expecter) Server() *Middleware_Server_Call {
	return &Middleware_Server_Call{Call: _e.mock.On("Server")}
}

func (_c *Middleware_Server_Call) Run(run func()) *Middleware_Server_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Middleware_Server_Call) Return(_a0 middleware.Server) *Middleware_Server_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Middleware_Server_Call) RunAndReturn(run func() middleware.Server) *Middleware_Server_Call {
	_c.Call.Return(run)
	return _c
}

// NewMiddleware creates a new instance of Middleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *Middleware {
	mock := &Middleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
